### ISSUE TITLE
Changing the domain 

### ISSUE THREAD

**Issue by clowxzz** [dtbsisco/RoFish#2]
i did this with ngrok and the website domain seeem so sus is there any way to change it 
https://4866-78-188-154-23.eu.ngrok.io

**Comment by BruhNessx** [comment]
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi (Sonny Digital)
1942, I take you back in that 'Rari

**Comment by SkyCreedPH** [comment]
LMFAO 💀💀💀💀😔💀😔💀😔💀

**Comment by xbxnz** [comment]
> i did this with ngrok and the website domain seeem so sus is there any way to change it https://4866-78-188-154-23.eu.ngrok.io

If you buy pro version of ngrok you can set up custom domains ($20)
https://ngrok.com/pricing
