### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by lhost25** [dtbsisco/RoFish#6]
nice job. can you make this capture cookies? it will be great if you can make this capture cookies instead of just user and pass.

i look forward to your response @dtbsisco

**Comment by dtbsisco** [comment]
yoo, I've been thinking about this and I might make a new project

**Comment by lhost25** [comment]
I look forward to that.
maybe using php to send result to email as option instead of store on server.

Thanks for your time and i look forward to your response @dtbsisco

**Comment by dtbsisco** [comment]
let me know your discord if you have.

**Comment by lhost25** [comment]
> let me know your discord if you have.

Yes i do @dtbsisco. my discord is smssmms.

**Comment by lhost25** [comment]
> let me know your discord if you have.

Hey bro, i did not eventually hear from you. I hope you are good?
@dtbsisco

**Comment by dtbsisco** [comment]
a small showcase
![image](https://github.com/user-attachments/assets/160abc3a-8041-4b8b-a783-8688b8388ff7)
